networks:
  inception:

volumes:
  wordpress_data:
  mariadb_data:

services:

  mariadb:
    image: "i-mariadb:1.0.0"
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/data/
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    image: "i-wordpress:1.0.0"
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html/
    networks:
      - inception

  nginx:
    image: "i-nginx:1.0.0"
    build: ./requirements/nginx
    ports:
     - "4444:443"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html/
    networks:
      - inception

  adminer:
    image: "i-adminer:1.0.0"
    build: ./requirements/bonus/adminer
    env_file:
      - .env
    networks:
      - inception

  grafana:
    image: "i-grafana:1.0.0"
    build: ./requirements/bonus/grafana
    env_file:
      - .env
    networks:
      - inception
  
  redis:
    image: redis:6.2
    build: ./requirements/bonus/redis
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html/
    networks:
      - inception
